spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # 请求服务是小写的时候改成true（默认为false轻微服务必须是大写）
      routes:
        - id: user-tenant
          uri: lb://user-tenant  # 服务端 service_id
          # 网关断言匹配
          predicates:
            - Path=/**    # 路由映射路径 这里注意，这个路径会追加到 service_id后
#          filters:
#            - StripPrefix=1  # 转发过滤前缀个数
        - id: record
          uri: lb://record  # 服务端 service_id
          # 网关断言匹配
          predicates:
            - Path=/**

ribbon:
  eureka:
    enabled: true # 开启eureka轮询
  eager-load:
    enabled: true  # 开启Ribbon的饥饿加载模式(防止第一次请求超时的问题)
#    clients: user-tenant # 指定需要开启的服务(需要开启Ribbon的饥饿加载模式)
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

#user-tenant:
#  ribbon:
#    listOfServers: 192.168.8.132:6001
